services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: pg_isready -d ${PGDATABASE} -U ${PGUSER}
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
