services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    healthcheck:
      test: curl "http://0.0.0.0:8080/health"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: pg_isready -d ${PGDATABASE} -U ${PGUSER}
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
    labels:
      stage: final
