openapi: 3.0.0

# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      description: "The needed authentication to use some of the services"
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
