/*
 * Split
 *
 * An easy way to split expenses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateUserPayload : The object required to create a new User
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserPayload {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl CreateUserPayload {
    /// The object required to create a new User
    pub fn new(username: String, password: String, description: String) -> CreateUserPayload {
        CreateUserPayload {
            username,
            password,
            description,
        }
    }
}

