/*
 * Split
 *
 * An easy way to split expenses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Default error response object. The given String never exposes internal infrastructure and can be shown to the client.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "reason")]
    pub reason: String,
}

impl ErrorResponse {
    /// Default error response object. The given String never exposes internal infrastructure and can be shown to the client.
    pub fn new(reason: String) -> ErrorResponse {
        ErrorResponse {
            reason,
        }
    }
}

