/*
 * Split
 *
 * An easy way to split expenses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : The user object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl User {
    /// The user object
    pub fn new(id: uuid::Uuid, username: String, description: String) -> User {
        User {
            id,
            username,
            description,
        }
    }
}

