name: Backend Integration Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install dependencies
        run: cargo fetch

      - name: Run Cargo fmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --bin split --no-deps -- -D warnings

      - name: Run Tests
        run: cargo test --all-targets

      # - name: Check SemVer compatibility
      #   uses: obi1kenobi/cargo-semver-checks-action@v2
  validate-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      # Cache Node.js modules and installed tools
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install swagger-cli
      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      # Validate all OpenAPI specs
      - name: Validate OpenAPI specs
        run: |
          set -e
          for file in $(find ./openapi -name '*.yaml'); do
            echo "Validating $file"
            if ! output=$(swagger-cli validate "$file" 2>&1); then
              echo "Validation failed for $file"
              echo "$(output)"
              exit 1
            else
              echo "Validation successful for $file"
            fi
          done
